### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by danielhoover** [fhkufstein-webdevelopment/ue03-wd2020-SabineAscher#1]
Liebe Frau Ascher,

Sie haben sich deutlich mehr Arbeit gemacht als Sie eigentlich müssten.

Vielleicht habe ich auch Mixins noch nicht gut genug erklärt.

Im Video habe ich versucht darzustellen, dass es lästig ist wenn man als Webentwickler dauernd irgendwelche Browser proprietären Präfixe verwenden muss. Was ist damit also gemeint?

```scss
.awesomeselector {
-moz-transition-property:width;
-o-transition-property:width;
-webkit-transition-property:width;
transition-property:width;
}
```

Eigentlich möchte man nur "transition-property" verwenden. Wegen ein paar Browsern ist man also als Entwickler gezwungen so viele Zeilen schreiben zu müssen. Durch den @import "compass/css3" haben wir ein paar Mixins includiert. Diese mixins sind auch bei compass-style dokumentiert. D.h. man müsste jetzt nur die richtigen Mixins heraussuchen.

Glücklicherweise gibt es einen mixin

```scss
.awesomeselector {
@include transition-property(width);
}
```

der das alles für uns erledigt. Richtig... Fertig! Der Präprozesser übersetzt den oberen Quelltext in das was wir wollten:

```scss
.awesomeselector {
-moz-transition-property:width;
-o-transition-property:width;
-webkit-transition-property:width;
transition-property:width;
}
```

Was Sie versucht haben ist einen Mixin selbst zu schreiben. Wobei Sie dabei den Parameter vergessen haben. Hätten Sie diesen Mixin jetzt selbst schreiben wollen (wobei Sie das ja in dieser Aufgabe noch nicht müssen) dann hätten Sie einfach

```scss
@mixin transition-property($property) {
-moz-transition-property:$property;
-o-transition-property:$property;
-webkit-transition-property:$property;
transition-property:$property;
}
```

schreiben können. Im Falle von dem transition property das bei compass mitgeliefert wird ist die Sache zwar etwas ausgefuchster programmiert - aber das Prinzip, denke ich, wird Ihnen dadurch klar.

Eine weitere Sichtweise auf Mixins wäre folgende:

Bei Variablen können Sie in der Regel nur eine Zeile Code verwenden. Bei einem mixin gehen mehrere Zeilen Code.

Ich hoffe Ihnen hat diese Erklärung geholfen!

Herzliche Grüße
Daniel Hoover
